### ISSUE TITLE
Notifications do not work

### ISSUE THREAD

**Issue by m1yon** [maxwowo/stando#10]
The "Send notifications to sit / stand" option does not work. I do not receive visual or audible notifications when transitioning between sitting to standing, regardless of the tone option. Here are my settings:

![CleanShot 2024-08-22 at 12 03 11](https://github.com/user-attachments/assets/b7b5e4ff-d532-4daa-aa90-5c85b47d2c35)

![CleanShot 2024-08-22 at 12 03 18](https://github.com/user-attachments/assets/28c24744-e97b-434c-97a8-83e3c2efe54c)

![CleanShot 2024-08-22 at 12 04 04](https://github.com/user-attachments/assets/e531ab8b-93d5-4c4d-ae80-e78fc922ea95)

**Comment by maxwowo** [comment]
Hey @m1yon ! Thanks for raising this issue. I'm currently on a gap year backpacking, so availability may be limited. Will look into it when I get some free time. Cheers!

**Comment by maxwowo** [comment]
Haha happens to the best of us! No worries, glad you like the app 😊
