### ISSUE TITLE
Custom reminder tones?

### ISSUE THREAD

**Issue by thomaswitt** [maxwowo/stando#2]
@maxwowo I love your app - thank you very much for your hard work. One little thing, it'd be great if it would support custom tones (e.g. the ones which you put under ~/Library/Sounds/) as reminders, as I often overhear the default system sound. What do you think?

**Comment by maxwowo** [comment]
Done, I've made a notifications settings tab that allows you to choose custom tones. It's going through App Store's review now and should be rolled out in a day or two's time

<img width="541" alt="image" src="https://github.com/maxwowo/stando/assets/40416283/e76cfb85-5f56-4095-9c27-1ef65a52f09c">

<img width="572" alt="image" src="https://github.com/maxwowo/stando/assets/40416283/b8016948-3d54-4936-b105-c380a7c7eea6">

**Comment by thomaswitt** [comment]
Wow -so cool … very much looking forward! I'll passt on my feedback as soon as it's updated. Happy Holidays!

**Comment by maxwowo** [comment]
Should be published to the App Store now! Let me know what you think

**Comment by thomaswitt** [comment]
@maxwowo Looks great… do you think there's a chance to:
- Choose other sounds than the default system sounds (I think ~/Library/Sounds/ is the default folder for that - Mail.app shows sounds located in there, Stando doesn't)
- Choose the Output Device
- Choose the Output Volume?

Basically the same like the system settings for Audio in macOS:
<img width="684" alt="MacOSAudioSettings" src="https://github.com/maxwowo/stando/assets/46834/4fe06003-df78-40ba-9083-e308739b0962">

**Comment by maxwowo** [comment]
@thomaswitt I did copy the sound files from `~/Library/Sounds`, is there one particular sound you'd like to use that Stando doesn't currently have?

I tried making it so that you can point Stando to custom sound files anywhere in the filesystem, but I was running into issues making Stando access these files and play the sounds, probably because of how macOS apps are containerized and don't have permission to them.

Regarding output device and volume, there wasn't an interface in the Swift UI API that allows notifications to be sent with volume / device specified. The most we can do is to just tell it which custom sound to play.

**Comment by thomaswitt** [comment]
I read into the docs, and yes, custom device and volume is tricky. But for _UNNotificationSound_ the docs (https://developer.apple.com/documentation/usernotifications/unnotificationsound) state:

_Audio files must already be on the user’s device before the system can play them. If you use a predefined set of sounds for your notifications, include the audio files in your app’s bundle. For all other sounds, the UNNotificationSound object looks only in the following locations:
- The /Library/Sounds directory of the app’s container directory.
- The /Library/Sounds directory of one of the app’s shared group container directories._

I didn't try how to get a list of them but maybe a simple 
_let soundFiles = try fileManager.contentsOfDirectory(atPath: directory)_
works for both directories?

**Comment by maxwowo** [comment]
Yep that's about what I also uncovered from my research, unfortunately it seems making Stando play any local sound resources is going to be a bit tedious. I'm currently working on another project so most of my attention will be directed there, you're more than welcome to have a go at the custom URL approach though! I can also look into it again when my other project ships
