### ISSUE TITLE
Stop when screensaver or powersave is on

### ISSUE THREAD

**Issue by ferent** [maxwowo/stando#4]
Hi!,

I can't confirm this is the culprit, but since some days ago it seems that my laptop is not sleeping correctly and I suspect is because Stando is running constantly, doesn't matter if the screensaver is on, the user has locked the computer or the laptop is in powersaving mode. 

Could you please check if it stops running during that periods of time, not only to save energy but I think it makes sense for it to stop counting if the enduser is not actively working/using their laptop.

Thanks for this great app.

**Comment by maxwowo** [comment]
Hmm that is weird 🤔 I'll look into it

**Comment by maxwowo** [comment]
Could you elaborate on how the laptop is not sleeping correctly? Is the battery draining much more quickly than usual

I remember doing a power consumption benchmark a while back and Xcode reported that Stando was using a negligible amount of power to keep track of time. It still makes sense to pause it when the laptop is going to sleep though 👍

**Comment by maxwowo** [comment]
Just confirmed that Stando does indeed run when the machine is sleeping, which drains the battery without providing any benefits. I've implemented a setting in the new release to allow Stando to pause when the machine is going into sleep. Will be submitting this to the App Store tonight. New version should be available in a day or two. Thanks for raising this issue!

![image](https://github.com/maxwowo/stando/assets/40416283/a03d3aac-3317-49fe-ad53-278094a30912)
