### ISSUE TITLE
Allow definition of active hours

### ISSUE THREAD

**Issue by Schaefers** [maxwowo/stando#8]
I have my Mac running all the time, but I just want to receive reminders from e.g. 8pm to 5am.

**Comment by maxwowo** [comment]
Hey @Schaefers! Thanks for the issue :) By active hours do you mean a time range that Stando should be running in, and it should automatically pause itself outside of that range? If so, would it suffice to just pause it manually when you no longer want to receive reminders?

**Comment by Schaefers** [comment]
> By active hours do you mean a time range that Stando should be running in, and it should automatically pause itself outside of that range?

Right. 

> If so, would it suffice to just pause it manually when you no longer want to receive reminders?

I could do that, but then I'll need a "Stando Reminder Enabler Reminder" which sends me a notification every morning to switch from pause to active 😄

**Comment by maxwowo** [comment]
Haha I see your point 😄 However, I still feel that this issue can be easily circumvented just by manually pausing / resuming when you leave for the day / come online at the start of the day. I want to keep the app as lightweight as possible and feel that adding active hours would bloat it up without giving too much benefits. Happy to reconsider though if there are more requests for this feature in the future 👍 

Alternatively, you're more than welcome to take the source code, tailor it for yourself, and publish it onto the App Store for your own consumption
